### ISSUE TITLE
index.html differs from the website

### ISSUE THREAD

**Issue by ilciavo** [ldionne/cppnow-2016-metaprogramming-for-dummies#1]
Thanks for the material. Comparing to the [website](http://ldionne.com/cppnow-2016-metaprogramming-for-dummies/#/) C++ code is missing on the slides: 
"Registering Classes",
"Classic Solution", 
"Optimizing Allignment", 
"Use std::tuple", 
"A Sequence that can hold different types", 
"Fortunately, there's hana", 
"Hana provides this static_type_info", 
"Tupe", 
"Indexing", 
"Inserting", 
"Removing", 
"Iterating", 
"Transforming",
"Filtering out", 
"Sorting", 
"Partitioning", 
"Searching", 
"Counting", 
"Reversing", 
"Unpacking", 
"Let's go back to allignment optimization", 
"Solution:using a tuple", 
"A more terse version", 
"Map", 
"Accesing Keys", 
"Querying", 
"Inserting", 
"Removing", 
"An example: an event system"...  
in the repository.

**Comment by ldionne** [comment]
Thanks for reporting. Would you happen to be using Google Chrome to view the presentation locally? If so, can you enable developer mode and check for errors in the console?

**Comment by ilciavo** [comment]
Thanks for the material. These are the errors from the console in Chrome. 
> XMLHttpRequest cannot load file:///Volumes/MacintoshHD/Users/Leo/Desktop/Code/C++/cppnow-2016-metaprogramming-for-dummies/code/classreg_naive.cpp. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
> send @ jquery.min.js:4

**Comment by ldionne** [comment]
That's because Javascript is [not allowed to load local files](http://stackoverflow.com/q/4819060/627587). It works on Safari and I think Firefox. I'm sorry, but there's nothing I can do (besides add a comment in the README).

**Comment by ilciavo** [comment]
Thanks, it works on safari. Cheers
